### PR TITLE
Merge DC Motor ROS Node

### PR DESCRIPTION
**Pull request by reuank**

### CODE REVIEW

**Comment by reuank** [comment]
@heyegross: Please check the code with 4 connected DC motors. Make sure to install the python library mentioned in the DC motor node before testing.
@mawalu: Could you add the mentioned library to the ansible and CI pipeline?

**Review by mawalu — CHANGES_REQUESTED** [review]
Some small remarks:
 * Could you put all the dependencies you need in a `requirements.txt` file so we can simple install them when needed
 * While my python experience is limited I have a feeling that `dc_motor_controller.py` would be much nicer as a class. This should at least limit the need for global variables

**Comment by reuank** [comment]
@mawalu, you are absolutely right. I am already working on the class-based implementation.
I'll add a requirements.txt as well. Thanks for the review!

**Review by mawalu — APPROVED** [review]
LGTM

**Pull request merged**
